baseURL = "https://yesqiao.github.io/"
languageCode = "en-us"
title = "The Blog"
theme = "beautifulhugo"

[params]
  Subtitle = "Written by YesQiao"
  Rss = true
  logo = "img/avatar-icon.jpg"

[Author]
    name = "YesQiao"
    github = "yesqiao"

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3